config_id = "Test Config"

[Game1]
scheme = "top_three"
max_ranking_points = -1
number_of_scores = 1
num_player_range = [4, 4]

[Game2]
scheme = "top_three"
max_ranking_points = -1
number_of_scores = 1
num_player_range = [8, 8]

[Game3]
scheme = "top_three"
max_ranking_points = -1
number_of_scores = 2
num_player_range = [2, 6]
